export const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEMS: "CLEAR_ITEMS",
  CHANGE_ITEM_QUANTITY: "CHANGE_ITEM_QUANTITY",
};
